-- DROP TABLE
DROP TABLE LECTURE;
DROP TABLE ENROLL;
DROP TABLE STUDENT;
DROP TABLE COURSE;
DROP TABLE PROFESSOR;

-- CREATE TABLE STUDENT PROFESSOR LECTURE ENROLL COURSE
CREATE TABLE PROFESSOR(
    P_NO    NUMBER            NOT NULL,
    P_NAME  VARCHAR2(20 BYTE),
    P_MAJOR VARCHAR2(30 BYTE)
);
CREATE TABLE COURSE(
    C_NO   NUMBER            NOT NULL,
    C_NAME VARCHAR2(30 BYTE),
    C_UNIT NUMBER(1)
);
CREATE TABLE STUDENT(
    S_NO       NUMBER             NOT NULL,
    S_NAME     VARCHAR2(20 BYTE),
    S_ADDRESS  VARCHAR2(100 BYTE),
    S_GRADE_NO NUMBER(1),
    P_NO       NUMBER             NOT NULL
);
CREATE TABLE ENROLL(
    E_NO   NUMBER NOT NULL,
    S_NO   NUMBER NOT NULL,
    C_NO   NUMBER NOT NULL,
    E_DATE DATE
);
CREATE TABLE LECTURE(
    L_NO       NUMBER            NOT NULL,
    P_NO       NUMBER            NOT NULL,
    E_NO       NUMBER            NOT NULL,
    L_NAME     VARCHAR2(50 BYTE),
    L_LOCATION VARCHAR2(30 BYTE)
);
-- ALTER TABLE
--PK
ALTER TABLE PROFESSOR
    ADD CONSTRAINT PK_PROFESSOR PRIMARY KEY(P_NO);
ALTER TABLE COURSE
    ADD CONSTRAINT PK_COURSE PRIMARY KEY(C_NO);
ALTER TABLE STUDENT
    ADD CONSTRAINT PK_STUDENT PRIMARY KEY(S_NO);
ALTER TABLE ENROLL
    ADD CONSTRAINT PK_ENROLL PRIMARY KEY(E_NO);
ALTER TABLE LECTURE
    ADD CONSTRAINT PK_LECTURE PRIMARY KEY(L_NO);
--FK
ALTER TABLE STUDENT
    ADD CONSTRAINT FK_STUDENT_PROFESSOR FOREIGN KEY(P_NO) REFERENCES PROFESSOR(P_NO);
ALTER TABLE ENROLL
    ADD CONSTRAINT FK_ENROLL_STUDENT FOREIGN KEY(S_NO) REFERENCES STUDENT(S_NO);
ALTER TABLE ENROLL
    ADD CONSTRAINT FK_ENROLL_COURSE FOREIGN KEY(C_NO) REFERENCES COURSE(C_NO);
ALTER TABLE LECTURE
    ADD CONSTRAINT FK_LECTURE_PROFESSOR FOREIGN KEY(P_NO) REFERENCES PROFESSOR(P_NO);
ALTER TABLE LECTURE
    ADD CONSTRAINT FK_LECTURE_ENROLL FOREIGN KEY(E_NO) REFERENCES ENROLL(E_NO);










