-- DROP TABLE
DROP TABLE LECTURE;
DROP TABLE ENROLL;
DROP TABLE STUDENT;
DROP TABLE COURSE;
DROP TABLE PROFESSOR;
-- CREATE TABLE STUDENT PROFESSOR LECTURE ENROLL COURSE
CREATE TABLE PROFESSOR(
    PRO_NO VARCHAR2(5 BYTE),
    PRO_NAME VARCHAR2(20 BYTE),
    PRO_MAJOR VARCHAR2(30 BYTE)
);
CREATE TABLE COURSE(
    COUR_NO VARCHAR2(5 BYTE),
    COUR_NAME VARCHAR2(30 BYTE),
    COUR_GRADE VARCHAR2(10 BYTE)
);
CREATE TABLE STUDENT(
    STU_NO VARCHAR2(5 BYTE),
    STU_NAME VARCHAR2(20 BYTE),
    STU_ADR VARCHAR2(100 BYTE),
    STU_AGE NUMBER(1),
    PRO_NO VARCHAR2(5 BYTE)
);
CREATE TABLE ENROLL(
    ENR_NO VARCHAR2(5 BYTE),
    STU_NO VARCHAR2(5 BYTE),
    COUR_NO VARCHAR2(5 BYTE),
    REGISTER DATE
);
CREATE TABLE LECTURE(
    LEC_NO VARCHAR2(5 BYTE),
    PRO_NO VARCHAR2(5 BYTE),
    ENR_NO VARCHAR2(5 BYTE),
    LEC_NAME VARCHAR2(50 BYTE),
    LOCATION VARCHAR2(30 BYTE)
);
-- ALTER TABLE
--PK
ALTER TABLE PROFESSOR
    ADD CONSTRAINT PK_PROFESSOR PRIMARY KEY(PRO_NO);
ALTER TABLE COURSE
    ADD CONSTRAINT PK_COURSE PRIMARY KEY(COUR_NO);
ALTER TABLE STUDENT
    ADD CONSTRAINT PK_STUDENT PRIMARY KEY(STU_NO);
ALTER TABLE ENROLL
    ADD CONSTRAINT PK_ENROLL PRIMARY KEY(ENR_NO);
ALTER TABLE LECTURE
    ADD CONSTRAINT PK_LECTURE PRIMARY KEY(LEC_NO);
--FK
ALTER TABLE STUDENT
    ADD CONSTRAINT FK_STUDENT_PROFESSOR FOREIGN KEY(PRO_NO) REFERENCES PROFESSOR(PRO_NO);
ALTER TABLE ENROLL
    ADD CONSTRAINT FK_ENROLL_STUDENT FOREIGN KEY(STU_NO) REFERENCES STUDENT(STU_NO);
ALTER TABLE ENROLL
    ADD CONSTRAINT FK_ENROLL_COURSE FOREIGN KEY(COUR_NO) REFERENCES COURSE(COUR_NO);
ALTER TABLE LECTURE
    ADD CONSTRAINT FK_LECTURE_PROFESSOR FOREIGN KEY(PRO_NO) REFERENCES PROFESSOR(PRO_NO);
ALTER TABLE LECTURE
    ADD CONSTRAINT FK_LECTURE_ENROLL FOREIGN KEY(ENR_NO) REFERENCES ENROLL(ENR_NO);










